### ISSUE TITLE
list of possible tags do write

### ISSUE THREAD

**Issue by wilkerlucio** [pandeiro/claudio#1]
Hi,

Could you please provide a list (extensible if possible) with all the possible keys to write on the song? I was trying to follow the Java library but the docs are really hard to figure out what are the possible options.

Thanks.

**Comment by pandeiro** [comment]
I think you'll need to drop down to Java if you want to be able to put "invalid" FieldKey names into your tag. Have you looked [here](http://www.jthink.net/jaudiotagger/maven/apidocs/org/jaudiotagger/tag/Tag.html)?

Meanwhile I've added an example to the README showing the fields JAudioTagger supports by default.

**Comment by wilkerlucio** [comment]
Thanks man :)
