### ISSUE TITLE
0.1.3 not pushed to clojars

### ISSUE THREAD

**Issue by vemv** [pandeiro/claudio#2]
0.1.3 is not here? https://clojars.org/claudio

Thanks for creating this library, will be useful to me!

Victor

**Comment by pandeiro** [comment]
[Done](https://clojars.org/claudio)! Sorry about that!

**Comment by vemv** [comment]
Nice!

ps - here's what I did with claudio ;p a key (as in "Ab maj") format converting script. Might turn it into a GUI app so others can use it.

https://github.com/vemv/traktor-keys/blob/master/src/traktor_keys/core.clj
